export const LIKE_QUESTION_SUCCESS = "LIKE_QUESTION_SUCCESS";
export const LIKE_QUESTION_FAIL = "LIKE_QUESTION_FAIL";

export const LIKE_QUESTION_UNDO_SUCCESS = "LIKE_QUESTION_UNDO_SUCCESS";
export const LIKE_QUESTION_UNDO_FAIL = "LIKE_QUESTION_UNDO_FAIL";

export const DISLIKE_QUESTION_SUCCESS = "DISLIKE_QUESTION_SUCCESS";
export const DISLIKE_QUESTION_FAIL = "DISLIKE_QUESTION_FAIL";

export const DISLIKE_QUESTION_UNDO_SUCCESS = "DISLIKE_QUESTION_UNDO_SUCCESS";
export const DISLIKE_QUESTION_UNDO_FAIL = "DISLIKE_QUESTION_UNDO_FAIL";

export const LIKE_ANSWER_SUCCESS = "LIKE_ANSWER_SUCCESS";
export const LIKE_ANSWER_FAIL = "LIKE_ANSWER_FAIL";

export const LIKE_ANSWER_UNDO_SUCCESS = "LIKE_ANSWER_UNDO_SUCCESS";
export const LIKE_ANSWER_UNDO_FAIL = "LIKE_ANSWER_UNDO_FAIL";

export const DISLIKE_ANSWER_SUCCESS = "DISLIKE_ANSWER_SUCCESS";
export const DISLIKE_ANSWER_FAIL = "DISLIKE_ANSWER_FAIL";

export const DISLIKE_ANSWER_UNDO_SUCCESS = "DISLIKE_ANSWER_UNDO_SUCCESS";
export const DISLIKE_ANSWER_UNDO_FAIL = "DISLIKE_ANSWER_UNDO_FAIL";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
