export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_LOGGED_IN_USER_START = "FETCH_LOGGED_IN_USER_START";
export const FETCH_LOGGED_IN_USER_SUCCESS = "FETCH_LOGGED_IN_USER_SUCCESS";
export const FETCH_LOGGED_IN_USER_FAIL = "FETCH_LOGGED_IN_USER_FAIL";
export const FETCH_LOGGED_IN_USER_RESET = "FETCH_LOGGED_IN_USER_RESET";

export const FETCH_LATEST_QUESTIONS_START = "FETCH_LATEST_QUESTIONS_START";
export const FETCH_LATEST_QUESTIONS_SUCCESS = "FETCH_LATEST_QUESTIONS_SUCCESS";
export const FETCH_LATEST_QUESTIONS_FAIL = "FETCH_LATEST_QUESTIONS_FAIL";

export const FETCH_HOT_QUESTIONS_START = "FETCH_HOT_QUESTIONS_START";
export const FETCH_HOT_QUESTIONS_SUCCESS = "FETCH_HOT_QUESTIONS_SUCCESS";
export const FETCH_HOT_QUESTIONS_FAIL = "FETCH_HOT_QUESTIONS_FAIL";

export const FETCH_TOP_USERS_START = "FETCH_TOP_USERS_START";
export const FETCH_TOP_USERS_SUCCESS = "FETCH_TOP_USERS_SUCCESS";
export const FETCH_TOP_USERS_FAIL = "FETCH_TOP_USERS_FAIL";

export const FETCH_USERS_QUESTIONS_START = "FETCH_USERS_QUESTIONS_START";
export const FETCH_USERS_QUESTIONS_SUCCESS = "FETCH_USERS_QUESTIONS_SUCCESS";
export const FETCH_USERS_QUESTIONS_FAIL = "FETCH_USERS_QUESTIONS_FAIL";

export const ADD_QUESTION_START = "ADD_QUESTION_START";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAIL = "ADD_QUESTION_FAIL";

export const LIKE_QUESTION_SUCCESS = "LIKE_QUESTION_SUCCESS";
export const LIKE_QUESTION_FAIL = "LIKE_QUESTION_FAIL";

export const LIKE_QUESTION_UNDO_SUCCESS = "LIKE_QUESTION_UNDO_SUCCESS";
export const LIKE_QUESTION_UNDO_FAIL = "LIKE_QUESTION_UNDO_FAIL";

export const DISLIKE_QUESTION_SUCCESS = "DISLIKE_QUESTION_SUCCESS";
export const DISLIKE_QUESTION_FAIL = "DISLIKE_QUESTION_FAIL";

export const DISLIKE_QUESTION_UNDO_SUCCESS = "DISLIKE_QUESTION_UNDO_SUCCESS";
export const DISLIKE_QUESTION_UNDO_FAIL = "DISLIKE_QUESTION_UNDO_FAIL";

export const LIKE_ANSWER_SUCCESS = "LIKE_ANSWER_SUCCESS";
export const LIKE_ANSWER_FAIL = "LIKE_ANSWER_FAIL";

export const LIKE_ANSWER_UNDO_SUCCESS = "LIKE_ANSWER_UNDO_SUCCESS";
export const LIKE_ANSWER_UNDO_FAIL = "LIKE_ANSWER_UNDO_FAIL";

export const DISLIKE_ANSWER_SUCCESS = "DISLIKE_ANSWER_SUCCESS";
export const DISLIKE_ANSWER_FAIL = "DISLIKE_ANSWER_FAIL";

export const DISLIKE_ANSWER_UNDO_SUCCESS = "DISLIKE_ANSWER_UNDO_SUCCESS";
export const DISLIKE_ANSWER_UNDO_FAIL = "DISLIKE_ANSWER_UNDO_FAIL";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
