export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_LOGGED_IN_USER_START = "FETCH_LOGGED_IN_USER_START";
export const FETCH_LOGGED_IN_USER_SUCCESS = "FETCH_LOGGED_IN_USER_SUCCESS";
export const FETCH_LOGGED_IN_USER_FAIL = "FETCH_LOGGED_IN_USER_FAIL";
export const FETCH_LOGGED_IN_USER_RESET = "FETCH_LOGGED_IN_USER_RESET";

export const FETCH_LATEST_QUESTIONS_START = "FETCH_LATEST_QUESTIONS_START";
export const FETCH_LATEST_QUESTIONS_SUCCESS = "FETCH_LATEST_QUESTIONS_SUCCESS";
export const FETCH_LATEST_QUESTIONS_FAIL = "FETCH_LATEST_QUESTIONS_FAIL";

export const FETCH_HOT_QUESTIONS_START = "FETCH_HOT_QUESTIONS_START";
export const FETCH_HOT_QUESTIONS_SUCCESS = "FETCH_HOT_QUESTIONS_SUCCESS";
export const FETCH_HOT_QUESTIONS_FAIL = "FETCH_HOT_QUESTIONS_FAIL";
